### ISSUE TITLE
Source code on Site

### ISSUE THREAD

**Issue by DraconicNEO** [Riivolution/riivolution.github.io#2]
Hello I wanted to ask if it would be possible for you to link the Source code of Riivolution on the site. A while ago AerialX decided to release Riivolution's source code along with RawkSD on his [repository](https://github.com/AerialX/rawksd)(Riivolution source code is in the Launcher folder).

**Comment by lilousky** [comment]
A link to the source code is available on the riivolution page of the site, although the repo is a clone of the one made public and as such it does not have the recent updates to riivolution's build system.
